const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Spritefont2,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Pin,
		C3.Behaviors.LOS,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.bound,
		C3.Plugins.TiledBg,
		C3.Behaviors.Physics,
		C3.Behaviors.Turret,
		C3.Behaviors.Fade,
		C3.Plugins.Particles,
		C3.Behaviors.Bullet,
		C3.Behaviors.Flash,
		C3.Behaviors.destroy,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.gamepad,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.JavaScriptInEvents.Esgame_Event2_Act41,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Spritefont2.Acts.SubInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Keyboard.Cnds.IsKeyCodeDown,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Bullet.Exps.AngleOfMotion,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Keyboard.Cnds.OnKeyCodeReleased,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Keyboard.Cnds.OnKeyCode,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.RotateCounterclockwise,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.gamepad.Cnds.OnAnyButtonUp,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.TiledBg.Cnds.CompareHeight,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Spritefont2.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.JavaScriptInEvents.Esgame_Event150_Act10,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Esgame_Event154_Act2,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.JavaScriptInEvents.Esgame_Event156_Act2,
		C3.JavaScriptInEvents.Esgame_Event157_Act2,
		C3.JavaScriptInEvents.Esgame_Event158_Act2,
		C3.JavaScriptInEvents.Esgame_Event158_Act37,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Behaviors.Turret.Acts.AcquireTarget,
		C3.Behaviors.Turret.Acts.SetRateOfFire,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.TiledBg.Cnds.CompareOpacity,
		C3.JavaScriptInEvents.Esgame_Event209_Act7,
		C3.JavaScriptInEvents.Esgame_Event210_Act1,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.JavaScriptInEvents.Esgame_Event212_Act1,
		C3.Plugins.System.Acts.SetTimescale,
		C3.JavaScriptInEvents.Esgame_Event213_Act8,
		C3.JavaScriptInEvents.Esgame_Event216_Act1,
		C3.JavaScriptInEvents.Esgame_Event217_Act8,
		C3.JavaScriptInEvents.Esgame_Event159_Act1,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.JavaScriptInEvents.Esfinalgame_Event2_Act1,
		C3.JavaScriptInEvents.Esfinalgame_Event2_Act2,
		C3.Plugins.Audio.Acts.SetMasterVolume
	];
};
self.C3_JsPropNameTable = [
	{valueChance: 0},
	{chances_SF: 0},
	{valueFuel: 0},
	{fuel_SF: 0},
	{valueMissiles: 0},
	{missiles_SF: 0},
	{missionNumber: 0},
	{amountMissions: 0},
	{missions_SF: 0},
	{amountMunitions: 0},
	{munition_SF: 0},
	{amountLives: 0},
	{lives_SF: 0},
	{ScrollTo: 0},
	{Pin: 0},
	{camera: 0},
	{LineOfSight: 0},
	{Pathfinding: 0},
	{BoundToLayout: 0},
	{camera_stalker: 0},
	{chain: 0},
	{activeMissile: 0},
	{activeMunition: 0},
	{startedEngine: 0},
	{burningFuel: 0},
	{fuelOver: 0},
	{helicopter: 0},
	{Physics: 0},
	{Turret: 0},
	{helipocter_ref: 0},
	{itemsDetector: 0},
	{propeller: 0},
	{shadow_helicopter: 0},
	{shotTargetRef: 0},
	{collected: 0},
	{barrel_fuel: 0},
	{box_munition: 0},
	{Fade: 0},
	{dust: 0},
	{explosion: 0},
	{explosionFragments: 0},
	{explosionMask: 0},
	{spark: 0},
	{trailSmoke: 0},
	{smoke_helicopter_crash: 0},
	{smoke_particle: 0},
	{distance: 0},
	{Bullet: 0},
	{munition: 0},
	{missile: 0},
	{missile_enemy: 0},
	{heliport: 0},
	{trees: 0},
	{garage_heliport: 0},
	{avenues: 0},
	{floor_texture: 0},
	{montain_bushes: 0},
	{tree_unit: 0},
	{bg_snow: 0},
	{Fade2: 0},
	{fade_intro: 0},
	{fade_transition_chances: 0},
	{village: 0},
	{initial_screen_BG: 0},
	{bg_credits: 0},
	{bg_finalGame: 0},
	{map: 0},
	{Flash: 0},
	{DestroyOutsideLayout: 0},
	{alertFuel: 0},
	{targetHelicopter: 0},
	{targetRadar: 0},
	{alertMissionCompleted: 0},
	{Sine: 0},
	{alert_takeoff: 0},
	{mission_completed_tick: 0},
	{labels_map: 0},
	{fuel_icon: 0},
	{message_all_missions_completed: 0},
	{life: 0},
	{aircraft_enemy: 0},
	{gunsFactory: 0},
	{bag_money: 0},
	{id: 0},
	{battery_ref: 0},
	{battery_base: 0},
	{battery: 0},
	{btn_playGame: 0},
	{btn_backMenu: 0},
	{btn_social_media: 0},
	{btn_social_media2: 0},
	{btn_credits: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Browser: 0},
	{Audio: 0},
	{Touch: 0},
	{btn_left_move: 0},
	{btn_right_move: 0},
	{btn_A: 0},
	{btn_B: 0},
	{btn_C: 0},
	{btn_D: 0},
	{btn_R: 0},
	{btn_L: 0},
	{btn_map: 0},
	{btn_left_MAP: 0},
	{btn_right_MAP: 0},
	{btn_Home: 0},
	{btn_forward: 0},
	{bg_infoScreen: 0},
	{arv_popup: 0},
	{nothanksanimation: 0},
	{watchnowanimation: 0},
	{watchtext: 0},
	{Gamepad: 0},
	{gaveSover: 0},
	{collectables: 0},
	{rescueMoneyBagMission: 0},
	{rv_ad_enabled: 0},
	{rv_popup: 0},
	{gunsFactoryMission: 0},
	{destroyAircraftMission: 0},
	{destroyBatteriesMission: 0},
	{isFallingDeathHelicopter: 0},
	{counter: 0},
	{missileEnemyScreen: 0},
	{hideMobileControls: 0},
	{ParameterX: 0},
	{ParameterY: 0},
	{ParameterLayer: 0},
	{rate: 0},
	{menu_index: 0},
	{sound: 0}
];

self.InstanceType = {
	chances_SF: class extends self.ISpriteFontInstance {},
	fuel_SF: class extends self.ISpriteFontInstance {},
	missiles_SF: class extends self.ISpriteFontInstance {},
	missions_SF: class extends self.ISpriteFontInstance {},
	munition_SF: class extends self.ISpriteFontInstance {},
	lives_SF: class extends self.ISpriteFontInstance {},
	camera: class extends self.ISpriteInstance {},
	camera_stalker: class extends self.ISpriteInstance {},
	chain: class extends self.ITiledBackgroundInstance {},
	helicopter: class extends self.ISpriteInstance {},
	helipocter_ref: class extends self.ISpriteInstance {},
	itemsDetector: class extends self.ISpriteInstance {},
	propeller: class extends self.ISpriteInstance {},
	shadow_helicopter: class extends self.ISpriteInstance {},
	shotTargetRef: class extends self.ISpriteInstance {},
	barrel_fuel: class extends self.ISpriteInstance {},
	box_munition: class extends self.ISpriteInstance {},
	dust: class extends self.ISpriteInstance {},
	explosion: class extends self.ISpriteInstance {},
	explosionFragments: class extends self.IParticlesInstance {},
	explosionMask: class extends self.ISpriteInstance {},
	spark: class extends self.ISpriteInstance {},
	trailSmoke: class extends self.ISpriteInstance {},
	smoke_helicopter_crash: class extends self.IParticlesInstance {},
	smoke_particle: class extends self.IParticlesInstance {},
	munition: class extends self.ISpriteInstance {},
	missile: class extends self.ISpriteInstance {},
	missile_enemy: class extends self.ISpriteInstance {},
	heliport: class extends self.ISpriteInstance {},
	trees: class extends self.ITiledBackgroundInstance {},
	garage_heliport: class extends self.ISpriteInstance {},
	avenues: class extends self.ISpriteInstance {},
	floor_texture: class extends self.ISpriteInstance {},
	montain_bushes: class extends self.ISpriteInstance {},
	tree_unit: class extends self.ISpriteInstance {},
	bg_snow: class extends self.ITiledBackgroundInstance {},
	fade_intro: class extends self.ITiledBackgroundInstance {},
	fade_transition_chances: class extends self.ITiledBackgroundInstance {},
	village: class extends self.ISpriteInstance {},
	initial_screen_BG: class extends self.ISpriteInstance {},
	bg_credits: class extends self.ISpriteInstance {},
	bg_finalGame: class extends self.ISpriteInstance {},
	map: class extends self.ITiledBackgroundInstance {},
	alertFuel: class extends self.ISpriteInstance {},
	targetHelicopter: class extends self.ISpriteInstance {},
	targetRadar: class extends self.ISpriteInstance {},
	alertMissionCompleted: class extends self.ISpriteInstance {},
	alert_takeoff: class extends self.ISpriteInstance {},
	mission_completed_tick: class extends self.ISpriteInstance {},
	labels_map: class extends self.ISpriteFontInstance {},
	fuel_icon: class extends self.ISpriteInstance {},
	message_all_missions_completed: class extends self.ISpriteInstance {},
	aircraft_enemy: class extends self.ISpriteInstance {},
	gunsFactory: class extends self.ISpriteInstance {},
	bag_money: class extends self.ISpriteInstance {},
	battery_ref: class extends self.ISpriteInstance {},
	battery_base: class extends self.ISpriteInstance {},
	battery: class extends self.ISpriteInstance {},
	btn_playGame: class extends self.ISpriteInstance {},
	btn_backMenu: class extends self.ISpriteInstance {},
	btn_social_media: class extends self.ISpriteInstance {},
	btn_social_media2: class extends self.ISpriteInstance {},
	btn_credits: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	btn_left_move: class extends self.ISpriteInstance {},
	btn_right_move: class extends self.ISpriteInstance {},
	btn_A: class extends self.ISpriteInstance {},
	btn_B: class extends self.ISpriteInstance {},
	btn_C: class extends self.ISpriteInstance {},
	btn_D: class extends self.ISpriteInstance {},
	btn_R: class extends self.ISpriteInstance {},
	btn_L: class extends self.ISpriteInstance {},
	btn_map: class extends self.ISpriteInstance {},
	btn_left_MAP: class extends self.ISpriteInstance {},
	btn_right_MAP: class extends self.ISpriteInstance {},
	btn_Home: class extends self.ISpriteInstance {},
	btn_forward: class extends self.ISpriteInstance {},
	bg_infoScreen: class extends self.ISpriteInstance {},
	arv_popup: class extends self.ISpriteInstance {},
	nothanksanimation: class extends self.ISpriteInstance {},
	watchnowanimation: class extends self.ISpriteInstance {},
	watchtext: class extends self.ISpriteInstance {},
	Gamepad: class extends self.IInstance {},
	gaveSover: class extends self.ISpriteInstance {},
	collectables: class extends self.ISpriteInstance {}
}